#!/bin/bash
# run as scripts/backup_fs /User/ubuntu/loomio-deploy
SOURCE_DIR=$1
BACKUP_DIR=$SOURCE_DIR/backups
DAY_OF_MONTH=`date '+%d'`
echo "day of month: $DAY_OF_MONTH"
echo "days retention: $BACKUP_RETENTION_DAYS"
DEST_FILE=$BACKUP_DIR/`hostname`-$(($DAY_OF_MONTH % $BACKUP_RETENTION_DAYS)).tgz

mkdir -p $BACKUP_DIR
tar cvzf $DEST_FILE -X "$SOURCE_DIR/.backup-ignore" $SOURCE_DIR
