#!/bin/bash
# run as scripts/backup_fs /User/ubuntu/loomio-deploy
SOURCE_DIR=$1
BACKUP_DIR=$SOURCE_DIR/backups
DEST_FILE=$BACKUP_DIR/`hostname`-`date '+%u'`.tgz

mkdir -p $BACKUP_DIR
tar cvzf $DEST_FILE -X "$SOURCE_DIR/.backup-ignore" $SOURCE_DIR
