#!/bin/bash
echo "backup - run as ./scripts/create_backup"

SOURCE_DIR=$(cd `dirname $0` && pwd)/..
BACKUP_DIR=$SOURCE_DIR/backups
DB_DUMP=$SOURCE_DIR/loomio_production.pg_dump
DEST_FILE=$BACKUP_DIR/`hostname`-`date '+%u'`.tgz
ERROR_FILE=$BACKUP_DIR/error.log
CONTAINER=loomio-deploy_db_1

echo "db dump file: $DB_DUMP"
echo "backup file: $DEST_FILE"
mkdir -p $BACKUP_DIR

echo "dumping db"
docker exec -ti $CONTAINER su - postgres -c 'pg_dump -Fc loomio_production' 1> $DB_DUMP 2> $ERROR_FILE

echo "dumping files"
tar cvzf $DEST_FILE -X .backup-ignore .
